### ISSUE TITLE
Test aliases don't allow for multiple cucumber tags to be run locally

### ISSUE THREAD

**Issue by tasharghyrou** [LandRegistry/common-dev-env#180]
I'm submitting a support/potential bug request

- [x] bug report

- [ ] feature request

- [x] support request

The alias for running acceptance tests does not appear to allow for multiple cucumber tags to be run at once anymore, I think it's due to an update in how the tags need to be formatted now with the following error message when trying to run in the comma-separated format that used to work:

`Found tags option '@TestCaseKey=E2E-T33,'. '@tag1,@tag2' is no longer supported, use '@tag or @tag2' instead. (RuntimeError)`

**What is the current behaviour?**
When using the command in the now supported format with the acctest alias (have also tried with various formats like putting the tags within '' or "") e.g:
`acctest digital-e2e-regression --tags @TestCaseKey=E2E-T33 or @TestCaseKey=E2E-T209`

The following error message occurs:
`No such file or directory - or. You can use `cucumber --init` to get started.`

When running the full command it will run the multiple tags successfully e.g:
`docker-compose run --rm digital-e2e-regression cucumber --color --format pretty --format html --out cucumber-report.html --format json --out test-report.json --tags '@TestCaseKey=E2E-T33 or @TestCaseKey=E2E-T209'`

So it's only when using the acctest alias that the error occurs

Example taken from our gitlabs test-common-components/regression/digital-e2e-regression repo but this is also affecting other teams.

**What is the expected/proposed behaviour?**
To be able to run multiple tags using the acctest alias again.

**What is the motivation / use case for changing the behaviour?**
Running multiple tags is a common thing for testers to do locally, and using the alias is the standard way to run tests. Right now, testers are running each tag individually and this would save them time and effort having to do multiple runs. We used to be able to run multiple tags locally before the previous comma separated way became unsupported

**Comment by chrisdebian** [comment]
Traced this through — the alias itself in this repo isn't the problem. `acctest`/`acceptance-test` correctly forwards `"${@:2}"`, preserving a quoted `--tags '@TestCaseKey=E2E-T33 or @TestCaseKey=E2E-T209'` argument as one piece all the way through `run` → `docker compose run`.

The actual bug is in the skeleton repo's `run_tests.sh`, which passes `$@` **unquoted** to cucumber on its last line. Unquoted `$@` word-splits on spaces, so the tag expression gets split back into separate arguments right before cucumber sees them — cucumber then treats the bare `or` as a positional argument (a feature-file path), producing exactly the reported error.

Opened a fix: [LandRegistry/skeleton-acceptance-tests#33](https://github.com/LandRegistry/skeleton-acceptance-tests/pull/33)

**Comment by sichapman** [comment]
"the alias itself in this repo isn't the problem" - while true right now, this is only because it was fixed earlier in #189, I'm guessing the AI that authored that comment did not have the history of changes as context.

**Comment by chrisdebian** [comment]
Good catch, thanks — you're right, that context was missing. #189 fixing the alias earlier is exactly why it traced clean when I looked at it. The underlying diagnosis for this issue still holds either way (the remaining bug was in skeleton-acceptance-tests's run_tests.sh, fixed in #33), but good to have the full history on record here.
